---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  deprecations_as_errors: true

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts sudo

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which initscripts net-tools sudo

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release net-tools sudo -y

- name: debian-9
  driver:
    image: debian:9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install systemd -y
      - RUN /usr/bin/apt-get install lsb-release net-tools sudo -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install net-tools sudo -y

- name: ubuntu-18.04
  driver:
    image: ubuntu:18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install net-tools sudo -y

suites:
  #
  # repository
  #
  - name: repository
    run_list:
      - recipe[test::repository]
  #
  # client_install
  #
  - name: client_install
    run_list:
      - recipe[test::client_install]
  #
  # server_install
  #
  - name: server_install
    run_list:
      - recipe[test::server_install]
  #
  # server_configuration
  #
  - name: server_configuration
    run_list:
      - recipe[test::server_configuration]
